### ISSUE TITLE
Great material! What you are using to create a blog? Anything like wordpress or cusotm code?

### ISSUE THREAD

**Issue by swapnil00patil** [amejiarosario/ama#11]
I really like the user experience you provide in blog. Which technology you use to create it? Any CMS like wordpress or cusotm code?

**Comment by amejiarosario** [comment]
@swapnil00patil I'm glad you like it! I used a JavaScript CMS called [Hexo](https://hexo.io/). In case you are familiar with Jekyll or Octopress, it's similar to it.

**Comment by amejiarosario** [comment]
Let me know if you have any particular question
