### ISSUE TITLE
Error: No picture file

### ISSUE THREAD

**Issue by raloliver** [amejiarosario/ama#14]
Hi Adrian... thank you for sharing your knowledge.

I tried to edit a product, and this product has a picture, but, I can not save without upload a new picture.

How I make this only when create a new product no in edition? 

![image](https://cloud.githubusercontent.com/assets/4580335/26578057/db8f29c0-4504-11e7-9006-0d93daccd625.png)

**Comment by amejiarosario** [comment]
Hi, sorry it took me so long to see this message. Let me know if you are still experiencing the issue.
