### ISSUE TITLE
Help with my M*EAN Stack App

### ISSUE THREAD

**Issue by partapparam** [amejiarosario/ama#17]
Hi Adrian, 

I've been struggling with the same error for over a week now and I can't seem to figure this out. It's getting frustrating. If you can provide any help and lead me in any direction, it would mean a lot. 

https://stackoverflow.com/questions/47022677/http-get-returns-index-html-code-not-data-from-php-database-call

Thank you for your time,

Param

**Comment by amejiarosario** [comment]
Sorry I didn't see this on time. Looks like you already got some answers.
