### ISSUE TITLE
are you open to new opportunities?

### ISSUE THREAD

**Issue by stewartsystems** [amejiarosario/ama#18]
Adrian,
You have a really interesting software development background, I know the team at Cisco in Cambridge and it is a great team doing great work.
I am a recruiter here in the Boston area and have some intriguing opportunities currently and wanted to ask if you might be open to having a conversation?
Jim Stewart Stewart Systems Inc. jim@stewartsystemsinc.com 207 655 9615

**Comment by amejiarosario** [comment]
No at the moment. Thanks for eaching out
