### ISSUE TITLE
Misspelling on your tutorial

### ISSUE THREAD

**Issue by emaag** [amejiarosario/ama#19]
Hi Adrian,, 

I came here from reddit and you have a good looking course, One thing though: 

In https://adrianmejia.com/blog/2018/04/04/how-you-can-change-the-world-learning-data-structures-algorithms-free-online-course-tutorial/ you write - "Alan’s team found out that every encrypted message ended with the same string: “Hail Hitler” Aha!! After changing the algorithm, the machine was used to save millions of lives!"  it should be Heil not Hail 

Eric

I

**Comment by amejiarosario** [comment]
Thanks a lot Eric! I just fixed it.

If find any other error or something is not clear, don't hesitate to point it out. 

@emaag You can also edit the post and send me the PR if that's more convenient for you :)
![blog-fix](https://user-images.githubusercontent.com/418605/40674212-1c6f419e-6342-11e8-8c32-944520899348.gif)
