### ISSUE TITLE
What does your dev environment look like? Hardware  + Software

### ISSUE THREAD

**Issue by AchoArnold** [amejiarosario/ama#2]

**Comment by amejiarosario** [comment]
![img_1161](https://cloud.githubusercontent.com/assets/418605/14928337/355a32dc-0e25-11e6-84a9-be365584bdfb.JPG)

_Hardware:_
- Mac Book Pro Laptop
- Two 27" displays

_Software_
- OS X El Capitan 10.11.4
- Atom/WebStorm
- iTerm2
