### ISSUE TITLE
building a multi vendor platform

### ISSUE THREAD

**Issue by snehalps** [amejiarosario/ama#20]
hello sir
i want to build a multi vendor platform like amazon...i have  zero experience with software development 
can you tell me how can i use your book for the same..
thank you
snehal ps

**Comment by amejiarosario** [comment]
Hi @snehalps,

My book provides the foundation for a single vendor. Multivendor is out of the scope unfortunately for that first edition. I'm planning to work on a 2nd edition that will include multi-vendor
