### ISSUE TITLE
DSA.js Book

### ISSUE THREAD

**Issue by shawnallen85** [amejiarosario/ama#22]
Is it possible to get it in a MOBI and EPUB format? Would like to have on my Kindle and Google Play Books.

Thanks!!
Shawn

**Comment by amejiarosario** [comment]
It's only available PDF at the moment, but I'm working on getting it converted to. I'll ping you once it's available.

**Comment by amejiarosario** [comment]
@shawnallen85 I sent an email with the book in new formats: ePub and Mobi. Let me know if that works ok for you.
