### ISSUE TITLE
Question in case of Building an e-commerce application with the MEAN stack

### ISSUE THREAD

**Issue by maxprog** [amejiarosario/ama#3]
Dear Adrian
I bought Your book "Building an e-commerce application with the MEAN stack" - it's very interesting. I use Windows system and my node's environment runs under this system. I see that Your source codes (samples attached to book) don't run under windows environment - during compilation I receive error.

Have You source code  which I can use under Windows?
## 

Best Regards
Grzegorz Kroczek

   blog: www.maxprog.net.pl
twitter: twitter.com/gregkroczek
gitHub:  github.com/maxprog
company: www.jrbsystem.com
 mobile: (+48) 606 519 794

**Comment by amejiarosario** [comment]
Hi Grzegorz,

Thanks for the interest on the book. Sorry for the delay, I was on vacation. 

Please check out the installation steps on https://github.com/amejiarosario/meanshop. I have been updating it. If you run into issues please post the full error messages [here](https://github.com/amejiarosario/meanshop/issues/new). Use that repo also for any other feedback regarding the book. That way I will be able to help you better.

Thanks,
Adrian
