### ISSUE TITLE
How do you get inspire to write web posts and books?

### ISSUE THREAD

**Issue by blancancabral** [amejiarosario/ama#4]

**Comment by amejiarosario** [comment]
Good question, well I could say have different sources of inspiration: 
1. **Exciment to try out new tech**: After trying out new technologies and making some side projects with it, I usually write a post about it.
2. **Frustration**: When I get frustrated about something that doesn't work, then when I figure it out I write posts with the solution.
3. **Interest**: I write books about thinks I'm interested about and have been using for some time.

**Comment by blancancabral** [comment]
Thanks, Adrian, I really liked "frustration".
