### ISSUE TITLE
Angular.js with EJS tied to express

### ISSUE THREAD

**Issue by vikramkhatri** [amejiarosario/ama#6]
Hi Adrian - Is there an example that you could share using EJS with Express and still using Angular at front end? Like your MEAN tutorial that you posed - which is a great help to learn but need to add EJS so that I have templates at the server. Jade is cool but I do not want to learn a new language so that is why I am looking at EJS or a better solution so that I have templates to avoid repeatation in views. As you figured it out already, I am new to all these. - Thanks for your time.

I am also reading your book on safaribooksonline.com. Let me see if I find what I am looking in your book.

**Comment by amejiarosario** [comment]
Hi @vikramkhatri,

Thanks for your interest and reading my book!

Just to clarify, Angular is meant to be used for **Single** Page Applications (SPA). That means, that you only will need a single HTML/EJS page, usually `index.ejs`.

In the following post, I generate an express app using EJS (I preferred over Jade, too):

http://adrianmejia.com/blog/2014/10/01/creating-a-restful-api-tutorial-with-nodejs-and-mongodb/#Bootstrapping-ExpressJS

Even tough it generates all the views, notice that we only use `index.ejs` on the project: 

https://github.com/amejiarosario/todoAPIjs/blob/master/views/index.ejs

All the views are generated on Angular. In the post, I have everything JS and Templates in a single page. It's easier for beginners. On the book, I show how to modularize the application. It also explains how to create many views in Angular. We also use a layout so we don't have to repeat code.

Let me know if my answer helps at all or if you have more questions.

**Comment by vikramkhatri** [comment]
Hi Adrian,

I finished reading 1st pass of your book and it has mountains of information that will take time to learn and implement.

I am still trying to learn a middle path – where to use express routing and how to blend with the routing at the angular level at page level.

Do you have an example of this? Or, do you think that it is a good idea or not to blend both routing.

Thank you

**Comment by amejiarosario** [comment]
@vikramkhatri I just added a new branch to the todoApp called `modular`: https://github.com/amejiarosario/todoAPIjs/tree/modular

Now, it is an example how to use express to route Angular apps. Notice that all the views folders are gone. Also, in express any route `app.get('*')` will get you the `index.html` page. Angular then takes control of the routing.

Take a look at this line: https://github.com/amejiarosario/todoAPIjs/blob/modular/public/javascripts/app.js#L72

Notice that based on the URL Angular knows what html file to render. You can add any other route and tell what HTML to render.

Check it out and let me know if it works for you.

**Comment by vikramkhatri** [comment]
Thank you Adrain. I will look at this. Am reading your book second time. Tons of info to digest especially for people like me who have been accustomed to sync type of programming. So switching to a async model is taking time to digest things.

**Comment by vikramkhatri** [comment]
Adrian,

What is your opinion on loopback as a framework for ReST API?

https://developer.ibm.com/open/events/dw-open-tech-talk-loopback/

**Comment by amejiarosario** [comment]
From what I see, Loopback uses ExpressJS behind the scenes (and MongoDB). I
haven't use it myself but looks nice.

**Comment by vikramkhatri** [comment]
Strongloop is the same company that developed express and then loopback. This company was acquired by IBM.

**Comment by amejiarosario** [comment]
Actually, ExpressJS was developed by @tj. And yes, nowadays, it's maintained by Strongloop.

**Comment by vikramkhatri** [comment]
I am looking loopback.io for examples. It looks very good. Will you consider writing a simple blog that explains this as you know this topic very well.

**Comment by amejiarosario** [comment]
That's a good idea @vikramkhatri! I'll put in the queue for when I finish writing the Angular 2 tutorials.
