### ISSUE TITLE
express router returning expected call back functions but got object undefined

### ISSUE THREAD

**Issue by brunokunta** [amejiarosario/ama#8]
'use strict';

var express = require('express');
var router = express.Router();
var auth = require('../../auth/auth.service');
var User = require('./user.model');
var json = require('../../helpers/json');
var controller = require('./user.controller');
var multiparty = require('connect-multiparty');
var uploadOptions = { autoFile: true,
                      uploadDir: 'material/assets/uploads/'
};

router.post('/', controller.create);
router.post('/authenticate', controller.authenticate);
router.get('/', controller.list);
router.post('/:userId/activate', controller.activate);
router.post('/resetPassword', controller.resetPassword);
router.post('/:userId/upload', multiparty(uploadOptions), controller.upload);
router.post('/:userId/invite', auth.isAuthenticated(), controller.invite);
router.post('/:userId/follow', auth.isAuthenticated(), controller.follow);
router.post('/:userId/unfollow', auth.isAuthenticated(), controller.unfollow);
router.get('/me', auth.isAuthenticated(), function(req, res) {
    if (req.user) {
      json.happy({
        record: req.user,
        token: req.token
      }, res);
    }
  });
router.get('/:userId', auth.isAuthenticated(), function(req, res){
    controller.single
});

router.get('/notifications', auth.isAuthenticated(), function(req, res){
    controller.notifications
});
router.get('/notificatins/:notficationId', auth.isAuthenticated(), function(req, res){
    controller.markRead
});
router.put('/', auth.isAuthenticated(), controller.modify);
router.get('/search/:keyword', auth.isAuthenticated(), function(req, res){
    controller.search
});

module.exports = router;

the error am getting i was getting is router.get/post  expected callback function but instead got object undefined then i read a stack-overflow post that recommended i try wrapping them in another callback function in the index.js file. After i didnt get any error when posting on controller.notifications, controller.markRead, controller.me and controller.single but i got server timeouts and the server is not responding with anything, i was wondering whether you could check it out for me.  here are the controllers for the affected routers. Please help me out cause i've been stuck on this for about a week now and i just cant seem to get it to work.

 module.exports.me = function(req, res) {
    if (req.user) {
      json.happy({
        record: req.user,
        token: req.token
      }, res);
    }
  }; 
module.exports.single = function(req, res) {
    /**
     \* The search criteria
     \* @type {Object}
     */
    var criteria = {};

```
/**
 * Can accept user's username
 */
criteria.username = req.params.userId;

User.findOne(criteria).populate('following').exec(function(err, user) {
  if (err) {
    return json.unhappy(err, res);
  } else if (user) {
    //now get followers
    return User.find({following: user._id}, function(err, followers) {
      if (err) {
        return json.unhappy(err, res);
      }
      return json.happy({
        record: user,
        followers: followers,
        following: user.following,
        alreadyFollowing: req.user.following.filter(function(item) {
          return item.username === user.username;
        }).length ? true : false
      }, res);
    });
  } else {
    return json.unhappy({message: 'User not found'}, res);
  }
});
```

  };

  /**
- Return a single user's notification
- @param  {Object} req Request
- @param  {Object} res Response
- @return {Void}  
  */
  module.exports.notifications = function(req, res) {
    User.findOne({_id: req.user._id, 'notifications.unread': true})
    .lean()
    .populate('notifications')
    .populate('notifications.post')
    .populate('notifications.user')
    .populate('notifications.actor')
    .exec(function(err, user) {
      if (err) {
        return json.unhappy(err, res);
      } else if (user) {
        user.notifications = user.notifications.filter(function(item) {
          return item.unread;
        });
        return json.happy({
          record: user,
          notifications: user.notifications.slice(0, 10)
        }, res);
      } else {
        return json.happy({message: 'No unread notifications.'}, res);
      }
    });
  };
  
  /**
- Return a single user's notification
- @param  {Object} req Request
- @param  {Object} res Response
- @return {Void}  
  */
  module.exports.markRead = function(req, res) {
    User.findOne({_id: req.user._id, 'notifications.unread': true})
    .populate('notifications')
    .populate('notifications.post')
    .populate('notifications.user')
    .exec(function(err, user) {
      if (err) {
        return json.unhappy(err, res);
      } else if (user) {
        //now get followers
        user.notifications.map(function(item) {
          if (item._id.toString() === req.params.notificationId) {
            item.unread = false;
          }
        });
        user.save(function () {
          user.notifications = user.notifications.filter(function(item) {
            return item.unread;
          });
          return json.happy({
            notifications: user.notifications.slice(0, 10)
          }, res);
        });
      } else {
        return json.happy({message: 'Already marked as unread.'}, res);
      }
    });
  };
  
  /**
- Self as json
- @param  {Object} req Request
- @param  {Object} res Response
- @return {Void}  
  */
  Those are all the affected controllers and routers. Please Mr. Mejia help me out.

**Comment by amejiarosario** [comment]
Hi @brunokunta,

Thanks for reaching out. I'd suggest you check out the source code from the [Meanshop repository](https://github.com/amejiarosario/meanshop) and then get to the chapter you are on. Here are the instructions:

https://github.com/amejiarosario/meanshop#source-code
